In [1]:
print('start')

start


In [10]:
#Indexing Numpy Arrays
import numpy as np
var = np.array([9,8,7,6]) #Extarcting the number 8 through slicing
print(var[1])

8


In [35]:
# Indexing 2d Numpy array
var=np.array([[1,2,3,4],[5,6,7,8]])
print('Dimension:',var.ndim,'d') # Checking the dimension of array
print(var)
print()
print('Task to get 7')
print(var[1,2],'Task Achieved') # Task to get 7 : First Axes(1) then index (2)  : Basically we have two axes which is 0,1


Dimension: 2 d
[[1 2 3 4]
 [5 6 7 8]]

Task to get 7
7 Task Achieved


In [46]:
# Indexing 3d Numpy Array
var=np.array([[[1,2,3,4,5,6],[11,12,13,14,15,16],[90,89,76,45,67,56]]])
print(f'Dimension:{var.ndim}d') # Checking the dimension
print(var)
print()
print('Task to get 14')
print(var[0,1,3],'Task Achieved') # Task to get 14 :first set:(0) then Axes(1) following that index(3)


Dimension:3d
[[[ 1  2  3  4  5  6]
  [11 12 13 14 15 16]
  [90 89 76 45 67 56]]]

Task to get 14
14 Task Achieved


In [62]:
#slicing 
var=([1,2,3,4,5,6,7,8])
print(var)
print()
print('Task to get 2 to 6:',var[1:6])  # Start index (1) then Stop Index (6)
print('Task to get start to end:', var[::]) # Automatically picked the value from starting to end
print('Task to get end to start:',var[::-1]) # start and end is set to deafault full sequence  step(-1) which moves backward (from right to left)

[1, 2, 3, 4, 5, 6, 7, 8]

Task to get 2 to 6: [2, 3, 4, 5, 6]
Task to get start to end: [1, 2, 3, 4, 5, 6, 7, 8]
Task to get end to start: [8, 7, 6, 5, 4, 3, 2, 1]


In [68]:
#Vetorized Operations : Performing the operation in entire array /series/column
import pandas as pd
# Series
data=[1,2,3,4,5,6,7]
opt=pd.Series(data)
vectorized=opt+5 #Evaluating operation
print(f'{vectorized}') # We have successfully perfrom the operation in series

0     6
1     7
2     8
3     9
4    10
5    11
6    12
dtype: int64


In [74]:
#Numpy
var=np.array([[[1,2,3,4,5,6],[11,12,13,14,15,16],[90,89,76,45,67,56]]])
var1=np.array([[[1,2,3,4,5,6],[11,12,13,14,15,16],[90,89,76,45,67,56]]])

add = var+var1
sub= var-var1
mul= var*var1

print(f'Additiion:{add}')
print(f'Subraction:{sub}')
print(f'Multiplication:{mul}') # We can perform thivectorized opteration in numpy as well

Additiion:[[[  2   4   6   8  10  12]
  [ 22  24  26  28  30  32]
  [180 178 152  90 134 112]]]
Subraction:[[[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]]
Multiplication:[[[   1    4    9   16   25   36]
  [ 121  144  169  196  225  256]
  [8100 7921 5776 2025 4489 3136]]]


In [76]:
#Element wise comparison
var=np.array([[[1,2,3,4,5,6],[11,12,13,14,15,16],[90,89,76,45,67,56]]])
if_greater=var>90
print(if_greater)


[[[False False False False False False]
  [False False False False False False]
  [False False False False False False]]]


In [77]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Sum all elements
total_sum = np.sum(arr)

# Sum along each column (axis 0)
column_sum = np.sum(arr, axis=0)

print("Total Sum:", total_sum)
print("Column-wise Sum:", column_sum)


Total Sum: 21
Column-wise Sum: [5 7 9]


In [81]:
#Filtering
arr=np.array([1,2,3,4])
arr=arr[arr>2]  #We can filter the value according to our need
arr

array([3, 4])

In [87]:
# Vectorized implementation of Mean Squared Error (MSE) cost function(Machine learning)
def compute_cost(X, y, theta):
    m = len(y)
    predictions = X.dot(theta)  # Vectorized prediction
    error = predictions - y
    cost = (1 / (2 * m)) * np.dot(error.T, error)  # Vectorized cost calculation
    return cost


X = np.array([[1, 1], [1, 2], [1, 3]])
y = np.array([1, 2, 3])
theta = np.array([0.1, 0.2])

cost = compute_cost(X, y, theta)
print(cost)


1.3383333333333332
